export interface NavItem {
  routeName: string;
  text: string;
  icon: string;
  requiresAuth?: boolean;
  requiresAdmin?: boolean;
  requiresPermission?: string;
  requiresFeature?: string;
  requiresVertical?: string;
  tenantOnly?: boolean;
  platformOnly?: boolean;
  tenantAdminOnly?: boolean;
  section?: string;
  requiresId?: boolean;
}

export const guestNavItems: NavItem[] = [
  { routeName: "home", text: "Home", icon: "mdi:home" },
  {
    routeName: "new-reservation",
    text: "New Reservation",
    icon: "mdi:calendar-plus",
  },
];

export const authenticatedNavItems: NavItem[] = [
  {
    routeName: "tenant-landing",
    text: "Dashboard",
    icon: "mdi:view-dashboard",
    requiresAuth: true,
  },
  {
    routeName: "reservations",
    text: "Reservations",
    icon: "mdi:format-list-bulleted",
    requiresAuth: true,
    requiresFeature: "dine_in",
  },
  {
    routeName: "table-management",
    text: "Tables",
    icon: "mdi:table",
    requiresAuth: true,
    requiresFeature: "table_management",
  },
  {
    routeName: "schedule",
    text: "Schedule",
    icon: "mdi:calendar",
    requiresAuth: true,
    requiresFeature: "staff_scheduling",
  },
  {
    routeName: "calendar",
    text: "Calendar",
    icon: "mdi:calendar",
    requiresAuth: true,
    requiresFeature: "dine_in",
  },
  {
    routeName: "staff-management",
    text: "Staff",
    icon: "mdi:account-group",
    requiresAuth: true,
    requiresFeature: "staff_scheduling",
  },
  {
    routeName: "floor-plan",
    text: "Floor Plan",
    icon: "mdi:map",
    requiresAuth: true,
    requiresFeature: "table_management",
  },
  {
    routeName: "floorplan-editor",
    text: "Floor Plan Editor",
    icon: "mdi:map-edit",
    requiresAuth: true,
    requiresPermission: "manage_tables",
    requiresFeature: "table_management",
  },
  {
    routeName: "waitlist",
    text: "Waitlist",
    icon: "mdi:clock",
    requiresAuth: true,
    requiresFeature: "waitlist",
  },
  {
    routeName: "reports",
    text: "Reports",
    icon: "mdi:chart-bar",
    requiresAuth: true,
  },
  {
    routeName: "custom-reports",
    text: "Report Builder",
    icon: "mdi:chart-areaspline",
    requiresAuth: true,
    requiresPermission: "view_reports",
  },
  {
    routeName: "reviews",
    text: "Reviews",
    icon: "mdi:star-outline",
    requiresAuth: true,
  },
  {
    routeName: "heatmap",
    text: "Heatmap",
    icon: "mdi:chart-area",
    requiresAuth: true,
    requiresFeature: "dine_in",
  },
  {
    routeName: "payments",
    text: "Payments",
    icon: "mdi:currency-usd",
    requiresAuth: true,
  },
  {
    routeName: "revenue-report",
    text: "Revenue",
    icon: "mdi:trending-up",
    requiresAuth: true,
  },
  {
    routeName: "search",
    text: "Search",
    icon: "mdi:magnify",
    requiresAuth: true,
  },
  {
    routeName: "about",
    text: "About",
    icon: "mdi:information",
    requiresAuth: true,
  },
  {
    routeName: "appointments",
    text: "Appointments",
    icon: "mdi:calendar-check",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-calendar",
    text: "Calendar",
    icon: "mdi:calendar-month",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-schedule",
    text: "Hours",
    icon: "mdi:clock-outline",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-walkins",
    text: "Walk-ins",
    icon: "mdi:account-clock",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-shifts",
    text: "Staff Shifts",
    icon: "mdi:calendar-clock",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "stations",
    text: "Stations",
    icon: "mdi:chair-rolling",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "station-map",
    text: "Station Map",
    icon: "mdi:map",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-services",
    text: "Services",
    icon: "mdi:content-cut",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-packages",
    text: "Packages",
    icon: "mdi:package-variant-closed",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-gift-cards",
    text: "Gift Cards",
    icon: "mdi:gift",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-referrals",
    text: "Referrals",
    icon: "mdi:account-group",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-gallery",
    text: "Gallery",
    icon: "mdi:image-multiple",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "erpnext-accounting",
    text: "Accounting",
    icon: "mdi:chart-pie",
    requiresAuth: true,
    requiresFeature: "erpnext_accounting",
  },
  {
    routeName: "erpnext-inventory",
    text: "Inventory",
    icon: "mdi:warehouse",
    requiresAuth: true,
    requiresFeature: "erpnext_stock",
  },
  {
    routeName: "erpnext-crm",
    text: "CRM",
    icon: "mdi:account-multiple",
    requiresAuth: true,
    requiresFeature: "erpnext_crm",
  },
  {
    routeName: "erpnext-employees",
    text: "Staff Records",
    icon: "mdi:account-group",
    requiresAuth: true,
    requiresFeature: "erpnext_hr",
  },
  {
    routeName: "erpnext-pos",
    text: "POS",
    icon: "mdi:cash-register",
    requiresAuth: true,
    requiresFeature: "erpnext_pos",
  },
  {
    routeName: "salon-inventory",
    text: "Inventory",
    icon: "mdi:warehouse",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-expenses",
    text: "Expenses",
    icon: "mdi:cash-minus",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-pricing",
    text: "Pricing Rules",
    icon: "mdi:tag-outline",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-settings",
    text: "Salon Settings",
    icon: "mdi:cog",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-reports",
    text: "Reports",
    icon: "mdi:chart-bar",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-recurring",
    text: "Recurring",
    icon: "mdi:repeat",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-clients",
    text: "Clients",
    icon: "mdi:account-group",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-dashboard",
    text: "Dashboard",
    icon: "mdi:view-dashboard",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-staff",
    text: "Staff",
    icon: "mdi:account-star",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-unified-schedule",
    text: "Unified Schedule",
    icon: "mdi:calendar-week",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-whatsapp-bookings",
    text: "WhatsApp Bookings",
    icon: "mdi:whatsapp",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-whatsapp-payments",
    text: "WhatsApp Payments",
    icon: "mdi:currency-usd",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-commissions",
    text: "Commissions",
    icon: "mdi:cash-multiple",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-marketing",
    text: "Marketing",
    icon: "mdi:bullhorn",
    requiresAuth: true,
    requiresVertical: "salon",
  },
  {
    routeName: "salon-gallery",
    text: "Gallery",
    icon: "mdi:image-multiple",
    requiresAuth: true,
    requiresVertical: "salon",
  },
];

export const adminNavItems: NavItem[] = [
  {
    routeName: "super-admin-overview",
    text: "Overview",
    icon: "mdi:view-dashboard",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Dashboard",
  },
  {
    routeName: "admin-settings",
    text: "Settings",
    icon: "mdi:cog",
    requiresAuth: true,
    requiresAdmin: true,
    platformOnly: true,
    tenantAdminOnly: true,
    section: "Platform",
  },
  {
    routeName: "tenant-dashboard",
    text: "Tenants",
    icon: "mdi:account-group",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-detail",
    text: "Venue Details",
    icon: "mdi:information",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-api-keys",
    text: "API Keys",
    icon: "mdi:key",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-branding",
    text: "Tenant Branding",
    icon: "mdi:palette",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-grace-period",
    text: "Grace Period",
    icon: "mdi:clock-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-notes",
    text: "Notes",
    icon: "mdi:note-text",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-timeline",
    text: "Tenant Timeline",
    icon: "mdi:timeline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-trial",
    text: "Tenant Trials",
    icon: "mdi:calendar-clock",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "tenant-invoices",
    text: "Tenant Invoices",
    icon: "mdi:file-document",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Financial",
  },
  {
    routeName: "tenant-onboarding",
    text: "Tenant Onboarding",
    icon: "mdi:clipboard-check",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "plans-management",
    text: "Pricing",
    icon: "mdi:tag-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-payment-dashboard",
    text: "Payments",
    icon: "mdi:currency-usd",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-usage",
    text: "Usage",
    icon: "mdi:chart-bar",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-revenue",
    text: "Revenue",
    icon: "mdi:trending-up",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-geographic",
    text: "Geographic",
    icon: "mdi:map-marker",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-bulk-actions",
    text: "Bulk Actions",
    icon: "mdi:check-all",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-financial",
    text: "Financial",
    icon: "mdi:currency-usd",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-feature-flags",
    text: "Feature Flags",
    icon: "mdi:flag",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-integrations",
    text: "Integrations",
    icon: "mdi:link",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-impersonation",
    text: "Impersonation",
    icon: "mdi:account-convert",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-settings",
    text: "Platform Settings",
    icon: "mdi:cog",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-sessions",
    text: "Sessions",
    icon: "mdi:desktop-classic",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-analytics",
    text: "Analytics",
    icon: "mdi:chart-box",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Dashboard",
  },
  {
    routeName: "billing-email-templates",
    text: "Billing Emails",
    icon: "mdi:email-send",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-backups",
    text: "Backups",
    icon: "mdi:database",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-alert-rules",
    text: "Alert Rules",
    icon: "mdi:bell-alert",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-maintenance",
    text: "Maintenance",
    icon: "mdi:wrench",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-trust-safety",
    text: "Trust & Safety",
    icon: "mdi:shield-check",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-support-tickets",
    text: "Support Tickets",
    icon: "mdi:ticket-account",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-support-templates",
    text: "Support Templates",
    icon: "mdi:text-box-check",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-support-chat",
    text: "Support Chat",
    icon: "mdi:chat",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-monitoring",
    text: "Monitoring",
    icon: "mdi:chart-line",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-api-latency",
    text: "API Latency",
    icon: "mdi:speedometer",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-cache-stats",
    text: "Cache Stats",
    icon: "mdi:memory",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-vertical-analytics",
    text: "Verticals",
    icon: "mdi:view-grid",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-vertical-templates",
    text: "Vertical Templates",
    icon: "mdi:file-document-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-compliance-rules",
    text: "Compliance Rules",
    icon: "mdi:shield-check-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-notification-templates",
    text: "Notification Templates",
    icon: "mdi:email-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-announcements",
    text: "Announcements",
    icon: "mdi:bullhorn-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-data-retention-policies",
    text: "Retention Policies",
    icon: "mdi:calendar-clock",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-penetration-tests",
    text: "Penetration Tests",
    icon: "mdi:security",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-insurance-documents",
    text: "Insurance Documents",
    icon: "mdi:file-certificate",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-encryption-keys",
    text: "Encryption Keys",
    icon: "mdi:key",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-auto-scaling",
    text: "Auto Scaling",
    icon: "mdi:chart-line-variant",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-compliance",
    text: "Compliance",
    icon: "mdi:shield-check",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-failover",
    text: "Failover",
    icon: "mdi:swap-horizontal",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-data-retention",
    text: "Data Retention",
    icon: "mdi:database-clock",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-audit-log",
    text: "Audit Log",
    icon: "mdi:clipboard-list",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-incidents",
    text: "Incidents",
    icon: "mdi:alert-circle",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-password-policy",
    text: "Password Policy",
    icon: "mdi:lock-check",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-suspicious-activity",
    text: "Suspicious Activity",
    icon: "mdi:account-alert",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-sub-processors",
    text: "Sub-Processors",
    icon: "mdi:cloud-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-reports",
    text: "Platform Reports",
    icon: "mdi:file-document-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "platform-reconciliation",
    text: "Reconciliation",
    icon: "mdi:currency-usd",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Financial",
  },
  {
    routeName: "platform-paystack",
    text: "Paystack Config",
    icon: "mdi:credit-card-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-whatsapp-delivery-failures",
    text: "WhatsApp Delivery Failures",
    icon: "mdi:whatsapp",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-shaqexpress-order-conversion",
    text: "Shaq Express Conversion",
    icon: "mdi:truck-delivery",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-whatsapp-support-ticket-analytics",
    text: "WhatsApp Support Analytics",
    icon: "mdi:chat-processing",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-marketplace",
    text: "Marketplace",
    icon: "mdi:store",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-case-studies",
    text: "Case Studies",
    icon: "mdi:book-open-variant",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-referrals",
    text: "Referrals",
    icon: "mdi:account-group",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Integrations",
  },
  {
    routeName: "platform-tenant-data-export",
    text: "Tenant Data Export",
    icon: "mdi:export",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "platform-cross-tenant-search",
    text: "Cross-Tenant Search",
    icon: "mdi:magnify",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "platform-data-anonymization",
    text: "Data Anonymization",
    icon: "mdi:incognito",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-debug",
    text: "Debug Tools",
    icon: "mdi:bug",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "platform-status",
    text: "System Status",
    icon: "mdi:heart-pulse",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Dashboard",
  },
  {
    routeName: "platform-migration",
    text: "Migrations",
    icon: "mdi:database-sync",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Platform",
  },
  {
    routeName: "platform-change-management",
    text: "Change Management",
    icon: "mdi:clipboard-text-clock",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "platform-postmortems",
    text: "Postmortems",
    icon: "mdi:post-outline",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "platform-fraud",
    text: "Fraud Prevention",
    icon: "mdi:shield-alert",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "platform-at-risk-tenants",
    text: "At-Risk Tenants",
    icon: "mdi:alert-circle",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Tenants",
  },
  {
    routeName: "platform-notifications",
    text: "Notifications",
    icon: "mdi:bell",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Support",
  },
  {
    routeName: "platform-benchmarks",
    text: "Benchmarks",
    icon: "mdi:chart-box",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    section: "Data & Tools",
  },
  {
    routeName: "tenant-dsar",
    text: "DSAR",
    icon: "mdi:shield-account",
    requiresAuth: true,
    requiresPermission: "manage_tenants",
    tenantOnly: true,
    platformOnly: true,
    requiresId: true,
    section: "Tenants",
  },
  {
    routeName: "role-management",
    text: "Roles",
    icon: "mdi:key",
    requiresAuth: true,
    tenantAdminOnly: true,
    section: "Platform",
  },
  {
    routeName: "group-management",
    text: "Groups",
    icon: "mdi:account-multiple",
    requiresAuth: true,
    tenantAdminOnly: true,
    section: "Platform",
  },
  {
    routeName: "audit-logs",
    text: "Audit",
    icon: "mdi:file-document-text",
    requiresAuth: true,
    tenantAdminOnly: true,
    section: "Security & Compliance",
  },
  {
    routeName: "email-templates",
    text: "Email Templates",
    icon: "mdi:email",
    requiresAuth: true,
    requiresAdmin: true,
    tenantAdminOnly: true,
    section: "Support",
  },
];

export const superAdminNavItems: NavItem[] = adminNavItems.filter(
  (item) => !item.tenantAdminOnly && !item.requiresId
);

export const tenantNavItems: NavItem[] = [
  ...authenticatedNavItems,
  ...adminNavItems.filter(
    (item) => item.requiresPermission !== "manage_tenants"
  ),
];
